### ISSUE TITLE
TODO Make the random generator seedable

### ISSUE THREAD

**Issue by gsimone** [pmndrs/maath#1]
```
// maybe with a global?
maath.random(seed) 

// or per method
random(a,b, { seed: 123 })
```

it should be fairly easy, gotta look for a solid & lightweight RNG package

**Comment by jamesporter** [comment]
I wanted a RNG for a project a couple of years ago. I pretty much gave up on figuring out which is the best (after the first popular option I picked seemed decidedly poor at randomness!) and I TypeScript-ified a JS implementation of supposedly good approach: https://github.com/jamesporter/solandra/blob/master/src/lib/rng.ts 

I don't actually understand how it works, but it is not very much code and allowed the thing I was making to be 'zero dependency'.

**Comment by gsimone** [comment]
Implemented a version of this 👯
